/**
 * @fileoverview RacesProvider — seeds races from 5etools data.
 *
 * Reads:
 *  - src/lib/5etools-data/races.json  — mechanical entries (traits, abilities, additionalSpells)
 *  - src/lib/5etools-data/fluff-races.json — lore descriptions and artwork
 * Creates: Race documents via RaceModel; Trait documents via TraitModel (on demand)
 * Looks up: Spell documents via SpellModel (never creates, only references)
 *
 * ─── Full flow per race item ──────────────────────────────────────────────────
 *
 *  processItem() — runs before user review:
 *   1. Skip NPC-only races and reprinted (superseded) races
 *   2. Map speed, size, source
 *   3. Image from fluff-races.json images[0].href.path
 *   4. Description from fluff-races.json entries (lore) → translated to PT
 *   5. Traits from races.json entries (mechanical) → translated to PT
 *   6. Spells from additionalSpells on base race → translated names stored as raw
 *      placeholder: { _raw: true, name: string (PT), level: number }
 *   7. Collect matching subraces as variations, same steps 3–6 per subrace
 *
 *  BaseProvider interactive loop:
 *   8. applyGlossaryToOutput() — apply glossary to names/descriptions/spell names
 *   9. Show user the translated JSON + allow glossary corrections
 *   10. User presses Enter (empty) to confirm or ESC to skip
 *
 *  afterReview() — runs after user confirms, before DB write:
 *   11. resolveTraits() — for base race and each variation:
 *       - Search Trait collection by name (case-insensitive regex)
 *       - Let user pick an existing one via terminal menu, or create new
 *       - Store in race as MENTION format (not full description):
 *         { name: "Habilidade sem Nome", level: 1, description: "<span data-type='mention' ...>" }
 *   12. resolveSpells() — for base race and each variation:
 *       - Search Spell collection by translated Portuguese name
 *       - If found: store as { id, name, circle, level } (circle from DB)
 *       - If NOT found: warn user to create the spell manually — never creates
 *   13. Create or update Race document in MongoDB
 *
 * ─── DB document structure ────────────────────────────────────────────────────
 *
 *  Race.traits[] (inline subdocuments):
 *    {
 *      _id: ObjectId,          // auto-generated by Mongoose
 *      name: "Habilidade sem Nome",  // always this default — display name for the slot
 *      level: 1,               // character level when trait is obtained
 *      description: '<span data-type="mention" data-id="TRAIT_OBJECTID"
 *                    data-entity-type="Habilidade" class="mention">Trait Name</span>'
 *    }
 *  → The actual trait content (full description, source) lives in the Trait collection
 *
 *  Race.spells[] (mixed schema):
 *    { id: "SPELL_OBJECTID", name: "Nome PT", circle: 0–9, level: 1|3|5|... }
 *  → circle = spell slot level (0 = cantrip, 1 = 1st level, etc.)
 *  → level  = character level at which the racial spell is obtained
 *
 * ─── 5etools additionalSpells format ─────────────────────────────────────────
 *
 *  additionalSpells is an array of spell group objects. We handle two sub-formats:
 *
 *   known.{charLevel}: ["spellName", "spellName#c", ...]
 *     → spells known permanently from character level {charLevel}
 *     → #c suffix = cantrip (circle 0); stripped before lookup
 *     → other suffixes (#o, #x) are also stripped
 *
 *   innate.{charLevel}.daily.{timesPerDay}: ["spellName", ...]
 *     → spells castable N×/day from character level {charLevel}
 *
 *   innate.{charLevel}.will: ["spellName", ...]
 *     → spells castable at will from character level {charLevel}
 *
 *   { choose: ... } entries are skipped — cannot be pre-populated automatically
 */

import path from 'path';
import fs from 'fs';
import { BaseProvider, convertFeetToMeters, formatSource } from '../base-provider';
import type { GlossaryEntry } from '../glossary/glossary-store';
import { applyGlossary } from '../glossary/glossary-store';
import type { CreateRaceInput, RaceTrait, RaceVariation, SizeCategory } from '../../../src/features/races/types/races.types';
import { RaceModel } from '../../../src/features/races/models/race';
import { Trait } from '../../../src/features/traits/database/trait';
import { Spell } from '../../../src/features/spells/models/spell';
import dbConnect from '../../../src/core/database/db';
import termKit from 'terminal-kit';

const term = termKit.terminal;
const PROJECT_ROOT = path.resolve(__dirname, '../../../');

// ─── 5etools input types ─────────────────────────────────────────────────────

interface FiveEToolsEntry {
    type?: string;
    name?: string;
    entries?: (string | FiveEToolsEntry)[];
    items?: (string | FiveEToolsEntry)[];
    entry?: string;
    caption?: string;
    colLabels?: string[];
    rows?: unknown[][];
}

export interface FiveEToolsRace {
    name: string;
    source: string;
    page?: number;
    size?: string[];
    speed?: number | Record<string, number | boolean>;
    ability?: Record<string, number>[];
    age?: { mature?: number; max?: number };
    traitTags?: string[];
    languageProficiencies?: Record<string, boolean | number>[];
    darkvision?: number;
    resist?: (string | Record<string, unknown>)[];
    entries?: FiveEToolsEntry[];
    hasFluff?: boolean;
    hasFluffImages?: boolean;
    reprintedAs?: string[];
    lineage?: string;
    additionalSpells?: AdditionalSpellGroup[];
    soundClip?: unknown;
}

export interface FiveEToolsSubrace {
    name?: string;
    source: string;
    raceName: string;
    raceSource: string;
    page?: number;
    size?: string[];
    speed?: number | Record<string, number | boolean>;
    ability?: Record<string, number>[];
    entries?: FiveEToolsEntry[];
    hasFluffImages?: boolean;
    reprintedAs?: string[];
    additionalSpells?: AdditionalSpellGroup[];
    _versions?: unknown[];
}

// ─── 5etools additionalSpells types ──────────────────────────────────────────

/**
 * A group of spells granted by the race/subrace.
 * `known` = always known; `innate` = castable N×/day or at will.
 * Keys are character level thresholds (as strings, e.g. "1", "3", "5").
 */
interface AdditionalSpellGroup {
    known?: Record<string, AdditionalSpellAtLevel>;
    innate?: Record<string, AdditionalSpellAtLevel>;
    ability?: string;
}

/**
 * Spells available at a specific character level threshold.
 * `_` = unconditional list; `daily.N` = N×/day; `will` = at-will.
 * Each value can be a plain string name or a `{ choose: ... }` object (skipped).
 */
interface AdditionalSpellAtLevel {
    _?: (string | Record<string, unknown>)[];
    daily?: Record<string, (string | Record<string, unknown>)[]>;
    will?: (string | Record<string, unknown>)[];
    rest?: Record<string, (string | Record<string, unknown>)[]>;
}

/**
 * A resolved spell reference not yet confirmed in the DB.
 * Used as a temporary placeholder in processItem() before afterReview()
 * searches the Spell collection and replaces it with the final format.
 *
 * Stored in `Race.spells[]` and `RaceVariation.spells[]` only until afterReview.
 * Never persisted to MongoDB.
 */
export interface RawSpellRef {
    _raw: true;
    /** Translated Portuguese spell name (from translateItem) */
    name: string;
    /** Character level at which this racial spell is granted */
    level: number;
}

interface FluffImageHref {
    type: 'internal' | 'external';
    path?: string;
    url?: string;
}

interface FluffImage {
    type: string;
    href: FluffImageHref;
}

interface FluffRaceEntry {
    name: string;
    source: string;
    entries?: (string | FiveEToolsEntry)[];
    images?: FluffImage[];
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const SIZE_MAP: Record<string, SizeCategory> = {
    S: 'Pequeno',
    M: 'Médio',
    L: 'Grande',
};

export function mapSize(sizeArr: string[] | undefined): SizeCategory {
    if (!sizeArr || sizeArr.length === 0) return 'Médio';
    for (const s of sizeArr) {
        const mapped = SIZE_MAP[s];
        if (mapped) return mapped;
    }
    return 'Médio';
}

function feetToMetersNum(feet: number): string {
    const m = feet * 0.3;
    return Number.isInteger(m) ? String(m) : m.toFixed(1).replace('.', ',');
}

const SPEED_LABELS: Record<string, string> = {
    walk: 'a pé',
    fly: 'voando',
    swim: 'nadando',
    climb: 'escalando',
    burrow: 'escavando',
};

export function mapSpeed(speed: number | Record<string, number | boolean> | undefined): string {
    if (speed === undefined) return '9 metros';

    if (typeof speed === 'number') {
        return `${feetToMetersNum(speed)} metros`;
    }

    const parts: string[] = [];
    for (const [key, value] of Object.entries(speed)) {
        const label = SPEED_LABELS[key] ?? key;
        if (typeof value === 'number') {
            parts.push(`${feetToMetersNum(value)} metros (${label})`);
        } else if (value === true) {
            if (key === 'fly') {
                parts.push('voo igual ao deslocamento a pé');
            } else {
                parts.push(`deslocamento de ${label} igual ao deslocamento a pé`);
            }
        }
    }

    return parts.join(', ') || '9 metros';
}


/** Strip 5etools inline tag syntax from text before sending to AI. */
export function cleanText(text: string): string {
    return text
        .replace(/\{@damage\s+([^}]+)\}/g, '$1')
        .replace(/\{@scaledamage\s+([^|]+)\|[^|]+\|([^}]+)\}/g, '$2')
        .replace(/\{@dice\s+([^}]+)\}/g, '$1')
        .replace(/\{@hit\s+([^}]+)\}/g, '+$1')
        .replace(/\{@dc\s+([^}]+)\}/g, 'CD $1')
        .replace(/\{@[a-z]+\s+([^}|]+)(?:\|[^}]*)?\}/gi, '$1')
        .trim();
}

export function buildEntryHtml(entry: FiveEToolsEntry | string): string {
    if (typeof entry === 'string') {
        return `<p>${cleanText(entry)}</p>`;
    }

    const parts: string[] = [];

    if (entry.type === 'list' && Array.isArray(entry.items)) {
        const listItems = entry.items
            .map((item) => {
                if (typeof item === 'string') return `<li>${cleanText(item)}</li>`;
                const e = item as FiveEToolsEntry;
                if (e.name && e.entry) {
                    return `<li><strong>${cleanText(e.name)}.</strong> ${cleanText(e.entry)}</li>`;
                }
                if (e.entry) return `<li>${cleanText(e.entry)}</li>`;
                if (e.entries) return `<li>${(e.entries as string[]).map(cleanText).join(' ')}</li>`;
                return '';
            })
            .filter(Boolean);
        parts.push(`<ul>${listItems.join('')}</ul>`);
    } else if (entry.type === 'table' && Array.isArray(entry.rows)) {
        // Skip complex tables in the seed description
    } else if (Array.isArray(entry.entries)) {
        const texts = entry.entries.map(buildEntryHtml).join('');
        if (entry.name) {
            parts.push(`<p><strong>${cleanText(entry.name)}.</strong></p>${texts}`);
        } else {
            parts.push(texts);
        }
    }

    return parts.join('');
}

export function buildDescriptionHtml(entries: (string | FiveEToolsEntry)[] | undefined): string {
    if (!entries || entries.length === 0) return '';
    return entries.map(buildEntryHtml).join('');
}

/** Extract named mechanical traits from a race's entries array. */
export function extractTraits(entries: FiveEToolsEntry[] | undefined): RaceTrait[] {
    if (!entries || entries.length === 0) return [];
    const traits: RaceTrait[] = [];
    for (const entry of entries) {
        if (typeof entry === 'string') continue;
        if (entry.name && Array.isArray(entry.entries)) {
            const descHtml = buildDescriptionHtml(entry.entries);
            if (descHtml) {
                traits.push({ name: cleanText(entry.name), description: descHtml, level: 1 });
            }
        }
    }
    return traits;
}

/**
 * Parses the 5etools `additionalSpells` array and returns a flat list of
 * `{ nameEN, charLevel }` pairs for fixed spell grants.
 *
 * Handled formats:
 *   - known.{charLevel}: string[]          — cantrips/spells always known
 *   - innate.{charLevel}.daily.N: string[] — castable N×/day at charLevel
 *   - innate.{charLevel}.will: string[]    — castable at-will at charLevel
 *   - innate.{charLevel}._: string[]       — unconditional list
 *
 * Skipped:
 *   - { choose: ... } entries — player choice, can't pre-populate
 *
 * @param additionalSpells - Raw 5etools additionalSpells array (may be undefined)
 * @returns Flat list of English spell names paired with their character-level threshold
 */
export function extractAdditionalSpells(
    additionalSpells: AdditionalSpellGroup[] | undefined,
): { nameEN: string; charLevel: number }[] {
    if (!additionalSpells || additionalSpells.length === 0) return [];

    const result: { nameEN: string; charLevel: number }[] = [];

    /**
     * Strips 5etools display-format suffixes from a spell name.
     * Examples: "dancing lights#c" → "dancing lights", "hold person#o" → "hold person"
     */
    const stripSuffix = (raw: string): string => raw.replace(/#[a-z]+$/, '').trim();

    /** Collect spells from an array, skipping `{ choose: ... }` objects. */
    const collectList = (list: (string | Record<string, unknown>)[], charLevel: number): void => {
        for (const entry of list) {
            if (typeof entry === 'string') {
                const nameEN = stripSuffix(entry);
                if (nameEN) result.push({ nameEN, charLevel });
            }
            // else: { choose: ... } — skip, cannot be pre-populated
        }
    };

    for (const group of additionalSpells) {
        // Process `known` section
        if (group.known) {
            for (const [levelStr, atLevel] of Object.entries(group.known)) {
                const charLevel = parseInt(levelStr, 10);
                if (isNaN(charLevel)) continue;
                // Handle both array shorthand and full AtLevel object
                if (Array.isArray(atLevel)) {
                    collectList(atLevel as (string | Record<string, unknown>)[], charLevel);
                } else if (atLevel && typeof atLevel === 'object') {
                    const typed = atLevel as AdditionalSpellAtLevel;
                    if (typed._) collectList(typed._, charLevel);
                    if (typed.daily) {
                        for (const list of Object.values(typed.daily)) collectList(list, charLevel);
                    }
                    if (typed.will) collectList(typed.will, charLevel);
                }
            }
        }

        // Process `innate` section
        if (group.innate) {
            for (const [levelStr, atLevel] of Object.entries(group.innate)) {
                const charLevel = parseInt(levelStr, 10);
                if (isNaN(charLevel)) continue;
                if (Array.isArray(atLevel)) {
                    collectList(atLevel as (string | Record<string, unknown>)[], charLevel);
                } else if (atLevel && typeof atLevel === 'object') {
                    const typed = atLevel as AdditionalSpellAtLevel;
                    if (typed._) collectList(typed._, charLevel);
                    if (typed.daily) {
                        for (const list of Object.values(typed.daily)) collectList(list, charLevel);
                    }
                    if (typed.will) collectList(typed.will, charLevel);
                    if (typed.rest) {
                        for (const list of Object.values(typed.rest)) collectList(list, charLevel);
                    }
                }
            }
        }
    }

    return result;
}

// ─── RacesProvider ────────────────────────────────────────────────────────────

export class RacesProvider extends BaseProvider<FiveEToolsRace, CreateRaceInput> {
    readonly name = 'Races';
    readonly dataFilePath = 'src/lib/5etools-data/races.json';
    readonly dataKey = 'race';

    private subraces: FiveEToolsSubrace[] = [];
    private fluffData: Map<string, FluffRaceEntry> = new Map();

    override readDataFile(): FiveEToolsRace[] {
        const fullPath = path.resolve(PROJECT_ROOT, this.dataFilePath);
        const raw = fs.readFileSync(fullPath, 'utf-8');
        const parsed = JSON.parse(raw) as Record<string, unknown>;

        const races = parsed[this.dataKey];
        if (!Array.isArray(races)) {
            throw new Error(`Key "${this.dataKey}" not found or not an array in ${fullPath}`);
        }

        this.subraces = Array.isArray(parsed['subrace'])
            ? (parsed['subrace'] as FiveEToolsSubrace[])
            : [];

        this.log(`Loaded ${this.subraces.length} subraces`, 'dim');

        // Load fluff data
        const fluffPath = path.resolve(PROJECT_ROOT, 'src/lib/5etools-data/fluff-races.json');
        const fluffRaw = fs.readFileSync(fluffPath, 'utf-8');
        const fluffParsed = JSON.parse(fluffRaw) as Record<string, unknown>;
        const fluffArr = Array.isArray(fluffParsed['raceFluff'])
            ? (fluffParsed['raceFluff'] as FluffRaceEntry[])
            : [];

        this.fluffData = new Map(fluffArr.map((f) => [`${f.name}|${f.source}`, f]));
        this.log(`Loaded ${this.fluffData.size} fluff entries`, 'dim');

        return races as FiveEToolsRace[];
    }

    private getFluff(name: string, source: string): FluffRaceEntry | undefined {
        return this.fluffData.get(`${name}|${source}`);
    }

    private buildFluffImageUrl(fluff: FluffRaceEntry | undefined): string {
        const img = fluff?.images?.[0];
        if (!img) return '';
        if (img.href.type === 'internal' && img.href.path) {
            return `https://5e.tools/img/${img.href.path}`;
        }
        if (img.href.type === 'external' && img.href.url) {
            return img.href.url;
        }
        return '';
    }

    async processItem(race: FiveEToolsRace): Promise<CreateRaceInput | null> {
        // Skip NPC-only races
        if (race.traitTags?.includes('NPC Race')) {
            this.log(`Skipping NPC race: ${race.name} (${race.source})`, 'dim');
            return null;
        }

        // Skip races superseded by a newer printing
        if (race.reprintedAs && race.reprintedAs.length > 0) {
            this.log(`Skipping reprinted race: ${race.name} (${race.source}) → ${race.reprintedAs[0]}`, 'dim');
            return null;
        }

        const fluff = this.getFluff(race.name, race.source);

        // Description comes from fluff lore entries
        const descriptionHtml = buildDescriptionHtml(fluff?.entries);
        const { name, description } = await this.translateItem(race.name, descriptionHtml);

        // Traits come from mechanical entries
        const rawTraits = extractTraits(race.entries);
        const translatedTraits: RaceTrait[] = [];
        for (const trait of rawTraits) {
            const { name: traitName, description: traitDesc } = await this.translateItem(
                trait.name,
                trait.description,
            );
            translatedTraits.push({ name: traitName, description: convertFeetToMeters(traitDesc) });
        }

        // Spells: extract from additionalSpells, translate names, store as raw placeholders.
        // afterReview() will resolve these placeholders against the Spell collection.
        const rawSpells = await this.translateSpellRefs(extractAdditionalSpells(race.additionalSpells));

        // Image from fluff
        const image = this.buildFluffImageUrl(fluff);

        // Map variations (subraces)
        const matchingSubraces = this.subraces.filter(
            (sr) => sr.raceName === race.name && sr.raceSource === race.source,
        );

        const variations: RaceVariation[] = [];
        for (const subrace of matchingSubraces) {
            // Skip reprinted subraces
            if (subrace.reprintedAs && subrace.reprintedAs.length > 0) continue;

            const subraceNameRaw = subrace.name ?? race.name;
            const subraceFluff = this.getFluff(subraceNameRaw, subrace.source);

            const subraceDescHtml = buildDescriptionHtml(subraceFluff?.entries);
            const { name: subraceName, description: subraceDescription } =
                await this.translateItem(subraceNameRaw, subraceDescHtml);

            const subraceRawTraits = extractTraits(subrace.entries);
            const subraceTraits: RaceTrait[] = [];
            for (const trait of subraceRawTraits) {
                const { name: traitName, description: traitDesc } = await this.translateItem(
                    trait.name,
                    trait.description,
                );
                subraceTraits.push({ name: traitName, description: convertFeetToMeters(traitDesc) });
            }

            // Spells for subrace: same translate-now, resolve-later approach
            const subraceRawSpells = await this.translateSpellRefs(
                extractAdditionalSpells(subrace.additionalSpells),
            );

            variations.push({
                name: subraceName,
                description: subraceDescription,
                source: formatSource(subrace.source, subrace.page),
                image: this.buildFluffImageUrl(subraceFluff),
                traits: subraceTraits,
                spells: subraceRawSpells,
                size: mapSize(subrace.size),
                speed: subrace.speed ? mapSpeed(subrace.speed) : undefined,
            });
        }

        return {
            name,
            originalName: race.name,
            description: convertFeetToMeters(description),
            source: formatSource(race.source, race.page),
            status: 'active',
            size: mapSize(race.size),
            speed: mapSpeed(race.speed),
            image,
            traits: translatedTraits,
            spells: rawSpells,
            variations,
        };
    }

    /**
     * Translates a list of English spell names (from extractAdditionalSpells) to
     * Portuguese using the configured translator.
     *
     * Returns `RawSpellRef[]` — placeholders that afterReview() will resolve against
     * the Spell collection. We only translate the name here (description = '').
     *
     * @param refs - List of { nameEN, charLevel } pairs from extractAdditionalSpells
     */
    private async translateSpellRefs(
        refs: { nameEN: string; charLevel: number }[],
    ): Promise<RawSpellRef[]> {
        const result: RawSpellRef[] = [];
        for (const { nameEN, charLevel } of refs) {
            const { name } = await this.translateItem(nameEN, '');
            result.push({ _raw: true, name, level: charLevel });
        }
        return result;
    }

    /** Called after glossary review — resolves each trait against the Trait collection. */
    protected override async afterReview(
        output: CreateRaceInput,
        isDryRun: boolean,
    ): Promise<CreateRaceInput> {
        if (isDryRun) return output;

        await dbConnect();

        // ── Step 1: Resolve traits ───────────────────────────────────────────
        // For each trait: search Trait collection, let user pick or create.
        // Stored in the race document as a mention span (not full description).
        const resolvedTraits = await this.resolveTraits(output.traits, output.name, output.source);

        const resolvedVariations: RaceVariation[] = [];
        for (const variation of output.variations) {
            const resolvedVarTraits = await this.resolveTraits(
                variation.traits,
                `${output.name} (${variation.name})`,
                output.source,
            );

            // ── Step 2: Resolve spells for this variation ──────────────────
            const resolvedVarSpells = await this.resolveSpells(
                variation.spells,
                variation.name,
            );

            resolvedVariations.push({ ...variation, traits: resolvedVarTraits, spells: resolvedVarSpells });
        }

        // ── Step 2: Resolve spells for base race ────────────────────────────
        const resolvedSpells = await this.resolveSpells(output.spells, output.name);

        return { ...output, traits: resolvedTraits, spells: resolvedSpells, variations: resolvedVariations };
    }

    /**
     * Resolves translated trait entries against the Trait collection.
     *
     * For each trait:
     *  - Searches by name (case-insensitive regex, up to 5 results)
     *  - If 0 results → creates a new Trait document with full description
     *  - If results → shows a terminal menu: pick existing or create new "<Name> (RaceName)"
     *
     * ⚠️ Storage format in the race document uses MENTION SPANS, not the full description.
     * This matches how the form saves traits: the race only holds a link to the Trait.
     *
     * Race trait stored format:
     *   { name: "Habilidade sem Nome", level: 1,
     *     description: '<span data-type="mention" data-id="TRAIT_ID"
     *                   data-entity-type="Habilidade" class="mention">Trait Name</span>' }
     *
     * The full trait content (description, source, status) lives in the Trait collection.
     */
    private async resolveTraits(
        traits: RaceTrait[],
        raceName: string,
        raceSource: string,
    ): Promise<RaceTrait[]> {
        if (traits.length === 0) return [];

        term.bold('\n─── Resolvendo Habilidades ─────────────────────────────────\n');

        const resolved: RaceTrait[] = [];

        for (const trait of traits) {
            term.cyan(`\n  Habilidade: `);
            term.bold(`${trait.name}\n`);

            const results = await Trait.find({
                name: { $regex: new RegExp(trait.name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i') },
            }).limit(5).lean();

            /** Build the mention span that is stored in the race document. */
            const buildMentionHtml = (id: string, traitName: string): string =>
                `<span data-type="mention" data-id="${id}" data-entity-type="Habilidade" class="mention">${traitName}</span>`;

            if (results.length === 0) {
                term.dim(`  → Nenhum resultado encontrado. Será criada.\n`);
                const created = await Trait.create({
                    name: trait.name,
                    description: trait.description,
                    source: raceSource,
                    status: 'active',
                });
                const traitId = String(created._id);
                term.green(`  ✓ Criada: "${trait.name}" (${traitId})\n`);

                resolved.push({
                    name: 'Habilidade sem Nome',
                    level: trait.level ?? 1,
                    description: buildMentionHtml(traitId, trait.name),
                });
                continue;
            }

            // Show existing results as formatted list
            term.dim(`\n  Resultados encontrados:\n`);
            results.forEach((r, i) => {
                term.dim(`  [${ i + 1 }] `);
                term.bold(`${r.name}\n`);
                const desc = r.description.replace(/<[^>]+>/g, '').substring(0, 120);
                term.dim(`       ${desc}${desc.length >= 120 ? '…' : ''}\n`);
                term.dim(`       id: ${String(r._id)}\n`);
            });

            const newName = `${trait.name} (${raceName})`;
            const menuItems = [
                `[0] CRIAR NOVA: "${newName}"`,
                ...results.map((r, i) => `[${i + 1}] USAR EXISTENTE: "${r.name}"`),
            ];

            term('\n');
            const choice = await new Promise<number>((resolve) => {
                term.singleColumnMenu(menuItems, (_, response) => {
                    resolve(response.selectedIndex);
                });
            });

            if (choice === 0) {
                const created = await Trait.create({
                    name: newName,
                    description: trait.description,
                    source: raceSource,
                    status: 'active',
                });
                const traitId = String(created._id);
                term.green(`  ✓ Criada: "${newName}" (${traitId})\n`);

                resolved.push({
                    name: 'Habilidade sem Nome',
                    level: trait.level ?? 1,
                    description: buildMentionHtml(traitId, newName),
                });
            } else {
                const picked = results[choice - 1];
                const traitId = String(picked._id);
                term.green(`  ✓ Usando existente: "${picked.name}" (${traitId})\n`);

                resolved.push({
                    name: 'Habilidade sem Nome',
                    level: trait.level ?? 1,
                    description: buildMentionHtml(traitId, picked.name),
                });
            }
        }

        term.bold('────────────────────────────────────────────────────────────\n');
        return resolved;
    }

    /**
     * Resolves translated spell name references against the Spell collection.
     *
     * Only processes entries with `_raw: true` (RawSpellRef) — these are translated
     * spell names produced by translateSpellRefs() in processItem().
     * Fully resolved spell objects `{ id, name, circle, level }` are passed through as-is.
     *
     * Resolution logic per raw spell:
     *  - Searches Spell collection by translated Portuguese name (case-insensitive regex)
     *  - 1 result  → uses it automatically, prints confirmation
     *  - N results → shows terminal menu for user to pick
     *  - 0 results → warns user to create the spell manually; NEVER creates a spell
     *
     * Final format stored in the race/variation document:
     *   { id: "SPELL_OBJECTID", name: "Nome PT", circle: 0–9, level: 1|3|5|... }
     *
     * @param spells    - Mixed array of RawSpellRef | resolved spell objects
     * @param raceName  - Used only in warning messages for context
     */
    private async resolveSpells(
        spells: unknown[],
        raceName: string,
    ): Promise<{ id: string; name: string; circle: number; level: number }[]> {
        if (spells.length === 0) return [];

        term.bold('\n─── Resolvendo Magias ──────────────────────────────────────\n');

        const resolved: { id: string; name: string; circle: number; level: number }[] = [];

        for (const spell of spells) {
            // Pass through already-resolved spells (e.g. from a prior run / findExisting)
            if (spell && typeof spell === 'object' && !('_raw' in spell)) {
                const s = spell as { id: string; name: string; circle: number; level: number };
                resolved.push(s);
                continue;
            }

            const raw = spell as RawSpellRef;
            term.cyan(`\n  Magia: `);
            term.bold(`${raw.name} (nível do personagem: ${raw.level})\n`);

            const results = await Spell.find({
                name: { $regex: new RegExp(raw.name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i') },
            }).limit(5).lean();

            if (results.length === 0) {
                term.yellow(`  ⚠  Magia "${raw.name}" não encontrada no banco.\n`);
                term.yellow(`     Crie-a manualmente e execute o script novamente para vinculá-la.\n`);
                continue;
            }

            let picked: typeof results[0];

            if (results.length === 1) {
                picked = results[0];
                term.green(`  ✓ Encontrada automaticamente: "${picked.name}" (circle: ${picked.circle})\n`);
            } else {
                term.dim(`\n  Múltiplos resultados encontrados:\n`);
                results.forEach((r, i) => {
                    term.dim(`  [${i + 1}] `);
                    term.bold(`${r.name}`);
                    term.dim(` (circle ${r.circle})\n`);
                });

                const menuItems = results.map((r, i) => `[${i + 1}] "${r.name}" (circle ${r.circle})`);
                term('\n');
                const choice = await new Promise<number>((resolve) => {
                    term.singleColumnMenu(menuItems, (_, response) => {
                        resolve(response.selectedIndex);
                    });
                });
                picked = results[choice];
                term.green(`  ✓ Selecionada: "${picked.name}"\n`);
            }

            resolved.push({
                id: String(picked._id),
                name: picked.name,
                circle: picked.circle,
                level: raw.level,
            });
        }

        term.bold('────────────────────────────────────────────────────────────\n');
        return resolved;
    }

    protected override applyGlossaryToOutput(output: CreateRaceInput, entries: GlossaryEntry[]): CreateRaceInput {
        const base = super.applyGlossaryToOutput(output, entries);

        const stripName = (s: string): string =>
            s.replace(/^[\s.,;:!?"']+|[\s.,;:!?"']+$/g, '').trim();

        const applyToTrait = (t: RaceTrait): RaceTrait => ({
            ...t,
            name: stripName(applyGlossary(entries, t.name)),
            description: applyGlossary(entries, t.description),
        });

        /**
         * Apply glossary to a spell entry.
         * Only processes RawSpellRef placeholders (translated names before DB lookup).
         * Fully resolved spell objects already have the canonical DB name — skip them.
         */
        const applyToSpell = (s: unknown): unknown => {
            if (s && typeof s === 'object' && '_raw' in s) {
                const raw = s as RawSpellRef;
                return { ...raw, name: applyGlossary(entries, raw.name) };
            }
            return s;
        };

        return {
            ...base,
            traits: base.traits.map(applyToTrait),
            spells: base.spells.map(applyToSpell),
            variations: base.variations.map((v) => ({
                ...v,
                name: stripName(applyGlossary(entries, v.name)),
                description: applyGlossary(entries, v.description),
                traits: v.traits.map(applyToTrait),
                spells: v.spells.map(applyToSpell),
            })),
        };
    }

    async findExisting(race: CreateRaceInput): Promise<CreateRaceInput | null> {
        await dbConnect();
        const escape = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const nameRegex = new RegExp(`^${escape(race.name)}$`, 'i');
        const orClauses: Record<string, unknown>[] = [{ name: nameRegex }];
        if (race.originalName) {
            orClauses.push({ originalName: new RegExp(`^${escape(race.originalName)}$`, 'i') });
        }
        const doc = await RaceModel.findOne({ $or: orClauses }).lean();
        if (!doc) return null;

        return {
            name: doc.name,
            originalName: doc.originalName,
            description: doc.description,
            source: doc.source,
            status: doc.status,
            size: doc.size,
            speed: doc.speed,
            image: doc.image ?? '',
            traits: doc.traits.map((t) => ({
                _id: t._id ? String(t._id) : undefined,
                name: t.name,
                description: t.description,
                level: t.level,
            })),
            spells: doc.spells,
            variations: doc.variations.map((v) => ({
                name: v.name,
                description: v.description,
                source: v.source,
                image: v.image ?? '',
                color: v.color,
                traits: v.traits.map((t) => ({
                    _id: t._id ? String(t._id) : undefined,
                    name: t.name,
                    description: t.description,
                    level: t.level,
                })),
                spells: v.spells,
                size: v.size,
                speed: v.speed,
            })),
        };
    }

    async create(race: CreateRaceInput): Promise<void> {
        await dbConnect();
        await RaceModel.create(race);
    }

    async update(race: CreateRaceInput): Promise<void> {
        await dbConnect();
        await RaceModel.findOneAndUpdate(
            { name: race.name },
            { $set: race },
            { runValidators: true },
        );
    }

    override getItemLabel(item: CreateRaceInput): string {
        return item.name;
    }
}
