openapi: 3.1.0
info:
  title: Rules API
  version: 1.0.0
paths:
  /api/rules:
    get:
      summary: List References
      parameters:
        - in: query
          name: search
          schema:
            type: string
        - in: query
          name: status
          schema:
            type: string
            enum: [active, inactive, all]
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        "200":
          description: Paginated list of rules
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Reference"
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer
    post:
      summary: Create Reference
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateReferenceInput"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reference"
  /api/rules/{id}:
    get:
      summary: Get Reference
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reference"
    put:
      summary: Update Reference
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateReferenceInput"
      responses:
        "200":
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reference"
    delete:
      summary: Delete Reference
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Deleted (or Archived)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean

components:
  schemas:
    Reference:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        source:
          type: string
        status:
          type: string
          enum: [active, inactive]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CreateReferenceInput:
      type: object
      required: [name, description, source]
      properties:
        name:
          type: string
        description:
          type: string
        source:
          type: string
        status:
          type: string
          default: active
    UpdateReferenceInput:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        source:
          type: string
        status:
          type: string
