openapi: 3.1.0
info:
  title: Upload API
  version: 1.0.0
paths:
  /api/upload:
    post:
      summary: Upload Image to S3
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: Public S3 URL
        "400":
          description: Invalid file type or too large
        "401":
          description: Unauthorized
